### PR TITLE
Support for script condition

### PR DESCRIPTION
**Pull request by tibee**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues |  |

### CODE REVIEW

**Comment by cebe** [comment]
can you show an example code on how you'd use it please?

**Comment by tibee** [comment]
Assume I have a decimal field named˛`flagfield`, in which I store many binary flags as bitwise summary.
For example, `101110` is stored as 46 decimal.

```php
$query->andWhere([
    "script",
    "(doc['flagfield'].value & 4) == 4",
]);
```

**Comment by beowulfenator** [comment]
I think it's a good idea to add support for script filters, but this isn't the best way of doing so. This implementation creates the same unfixable problem as the `addAggregation` function introduced earlier. Consider the structure of ES script filter:

```
{"script" : {
    "inline" : "doc['num1'].value > params.param1",
    "lang"   : "painless",
    "params" : {
        "param1" : 5
    }
}}
```

Let's extend your example slightly:

```
$query->andWhere([
    "script",
    "(doc['flagfield'].value & 4) == myval",
    ["myval" => 4]
]);
```

First operand is the string "script", second operand is the script itself. You are essentially taking the third operand (`["myval" => 4]`) and passing it as `params` to ElasticSearch.

As you see, there is no way to specify which language the script is in (the "lang" param). Sure, you could add the fourth optional operand. Also, there's no way to reference a script file. Sure, you could add the fifth optional operand. And keep adding more operands as ElasticSearch extends its DSL. This is not the way to go.

If you are so keen on having this simplfied implementation, let's do it this way. You can check whether the second operand (the script itself) is not an array. If it is not an array, do it your way. If it is an array, pass it as the object for the script filter:

```
$query->andWhere([
    "script",
    [
        "inline" => "doc['num1'].value > params.param1",
        "lang" => "painless",
        "params" => [
            "param1" => 5,
        ],
    ],
]);
```
becomes

```
{"script" : {
    "inline" : "doc['num1'].value > params.param1",
    "lang"   : "painless",
    "params" : {
        "param1" : 5
    }
}}
```

In any case, this is a worthwhile update, but it needs tests and docs too.

**Comment by tibee** [comment]
I see, the script operator can have different number of operands.

What do you think of having only 1 operand, an array, and you could pass any elements you want / ES supports. Inline, lang, params, whatever.

It would be even more simple than my commit.

**Pull request closed without merging**
