### PR TITLE
Fix di

### PR DESCRIPTION
**Pull request by raidkon**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | ?
| Fixed issues  | Fix di

### CODE REVIEW

**Comment by samdark** [comment]
@raidkon seems to fail tests.

**Comment by beowulfenator** [comment]
@samdark, this fails because of https://github.com/yiisoft/yii2-elasticsearch/pull/301
Is now the time to re-revert that PR?

**Comment by bizley** [comment]
It's corrected already, only awaits 2.0.42 release.

**Comment by samdark** [comment]
Alright. @beowulfenator what do you think about this change?

**Comment by beowulfenator** [comment]
> Alright. @beowulfenator what do you think about this change?

I'm sorry, I have zero experience with DI. Looks legit, but what do I know? :)

**Comment by bizley** [comment]
I'm not sure about this. While it will benefit from container definition setting for sure it will be slower now. Is there a valid use case?

**Comment by samdark** [comment]
@raidkon what's your use case?

**Comment by samdark** [comment]
@bizley it's now released. Tests still fail, it seems.

**Comment by bizley** [comment]
It seems to be because of https://github.com/yiisoft/yii2/commit/54f25c4b04a0c1fb24b9c9583c878555f5d1ecef#diff-78dc0b3aa7bc8f25f23245e9739f7b411ca14be977bdec098fde0d672618c48e 
I'll try to fix the problem.

**Comment by bizley** [comment]
It looks like it's better to fix it in the core. I've missed the fact that most ActiveQuery versions don't have `on` property.

**Comment by samdark** [comment]
Alright. Solved now :)

**Comment by samdark** [comment]
@raidkon would you please add a changelog and a test for the change?

**Comment by bizley** [comment]
Since @raidkon is not eager to provide test for this or even a use case I vote for closing it.

**Pull request closed without merging**
