### PR TITLE
Fix #15 ActiveDataProvider

### LINKED ISSUE #15: Create ElasticSearch `ActiveDataProvider`
Need to consider creating ElasticSearch specific `ActiveDataProvider`, which can use search result meta information for total item count and pagination.
It should be similar to the one created for Sphinx:
https://github.com/yiisoft/yii2-sphinx/blob/master/ActiveDataProvider.php

### PR DESCRIPTION
**Pull request by klimov-paul**
Fix #15 : Create ElasticSearch `ActiveDataProvider`.

Here is an imlementation as I can compose it.

Note: I don't have an environment to test this, and thus have no ability for further improvement.
You can use this PR as a start point for the final implementation.

### CODE REVIEW

**Comment by andrey-yantsen** [comment]
Just checked it, works perfectly. Why it's not yet merged to master? :)

**Comment by zinzinday** [comment]
Why not mere this reduce more 1/2 of time for query jobs?

**Comment by cebe** [comment]
> Why not merge this

need time to review. I am stuck with other things for at least two weeks. afterwards I might get to merge this.

**Comment by klimov-paul** [comment]
Merged manually

**Pull request merged**
