### PR TITLE
Fix error of debug page

### PR DESCRIPTION
**Pull request by jafaripur**
Error occurred when $messages variable is null and this exception throw:

``Invalid argument supplied for foreach()``

### CODE REVIEW

**Comment by beowulfenator** [comment]
Hi! When is `$messages` null?

**Comment by samdark** [comment]
How to reproduce it?

**Comment by jafaripur** [comment]
I haven't any query in Elasticsearch yet, but just after run any page and open debug page in new tab this error throw.

**Comment by cebe** [comment]
can you please show the complete stack trace of the error?

**Comment by jafaripur** [comment]
```

1. in /var/www/html/crawler/vendor/yiisoft/yii2-elasticsearch/DebugPanel.php at line 163
154155156157158159160161162163164165166167168169170171172

 
    public function calculateTimings()
    {
        if ($this->_timings !== null) {
            return $this->_timings;
        }
        $messages = $this->data['messages'];
        $timings = [];
        $stack = [];
        foreach ($messages as $i => $log) {
            list($token, $level, $category, $timestamp) = $log;
            $log[5] = $i;
            if ($level == Logger::LEVEL_PROFILE_BEGIN) {
                $stack[] = $log;
            } elseif ($level == Logger::LEVEL_PROFILE_END) {
                if (($last = array_pop($stack)) !== null && $last[0] === $token) {
                    $timings[$last[5]] = [count($stack), $token, $last[3], $timestamp - $last[3], $last[4]];
                }
            }

2. in /var/www/html/crawler/vendor/yiisoft/yii2-elasticsearch/DebugPanel.php at line 163 – yii\base\ErrorHandler::handleError(2, 'Invalid argument supplied for fo...', '/var/www/html/crawler/vendor/yii...', 163, ...)
157158159160161162163164165166167168169

        if ($this->_timings !== null) {
            return $this->_timings;
        }
        $messages = $this->data['messages'];
        $timings = [];
        $stack = [];
        foreach ($messages as $i => $log) {
            list($token, $level, $category, $timestamp) = $log;
            $log[5] = $i;
            if ($level == Logger::LEVEL_PROFILE_BEGIN) {
                $stack[] = $log;
            } elseif ($level == Logger::LEVEL_PROFILE_END) {
                if (($last = array_pop($stack)) !== null && $last[0] === $token) {

3. in /var/www/html/crawler/vendor/yiisoft/yii2-elasticsearch/DebugPanel.php at line 50 – yii\elasticsearch\DebugPanel::calculateTimings()
44454647484950515253545556

 
    /**
     * @inheritdoc
     */
    public function getSummary()
    {
        $timings = $this->calculateTimings();
        $queryCount = count($timings);
        $queryTime = 0;
        foreach ($timings as $timing) {
            $queryTime += $timing[3];
        }
        $queryTime = number_format($queryTime * 1000) . ' ms';

4. in /var/www/html/crawler/vendor/yiisoft/yii2-debug/views/default/index.php at line 24 – yii\elasticsearch\DebugPanel::getSummary()
18192021222324252627282930

            <div class="yii-debug-toolbar__block yii-debug-toolbar__title">
                <a href="#">
                    <img width="29" height="30" alt="" src="<?= \yii\debug\Module::getYiiLogo() ?>">
                </a>
            </div>
            <?php foreach ($panels as $panel): ?>
                <?= $panel->getSummary() ?>
            <?php endforeach; ?>
        </div>
    </div>
 
    <div class="container">
        <div class="row">
```

**Comment by cebe** [comment]
Thank you, reproduced the issue, it theoretically exists in all Panels but only pops up here as the panel is added after other debug data has been created already. data for ES panel is empty.

The weird thing is that it does not fail in the lines above with 'Undefined index' because data is not an array.

See https://3v4l.org/bRVnR

```php
<?php

error_reporting(-1);

$data = null;
$messages = $data['messages'];
var_dump($messages);

$data = [];
$messages = $data['messages'];
var_dump($messages);
```

which outputs only one Notice, the null case seems to run without error.

```
NULL

Notice: Undefined index: messages in /in/bRVnR on line 10
NULL
```

Always learning something new...

**Comment by cebe** [comment]
Merged with small adjustment, thank you!

**Pull request closed without merging**
