### PR TITLE
Fixed Query::source() when $source = `false`

### PR DESCRIPTION
**Pull request by rhertogh**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

The source field can be set to `false` in which case no source will be returned (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#source-filtering).

Before this fix when passing `false` to the `source` function it would be passed as an array (`[false]` by Yii to ElasticSearch. This would cause ElasticSearch to treat it as field which it tries to match. Since there is often no field called 'false' no source is returned. Therefore it might seem that the old code works, but since ElasticSearch does try to find the non-existing field for each document this has a huge performance impact. On a small test index it almost doubles the time it takes to perform the query (45ms vs the original 82ms (average of 10 requests)).

### CODE REVIEW

**Comment by rhertogh** [comment]
All tests only seem to fail at the known "yii\db\Connection is expected." bug.

**Comment by beowulfenator** [comment]
@rhertogh, can you remind me what the difference between source==false and source==null is?

**Comment by rhertogh** [comment]
@beowulfenator 
> can you remind me what the difference between source==false and source==null is?

The difference is caused by the strict type checking. In the example above there isn't actually any difference since the operant is `==`. In the source code `===` is used. By using the "triple equals" operant not only the value but also the data type must be equal for the equation to be `true`.

**Comment by beowulfenator** [comment]
No, i mean why would somebody who's using the library write `->source(false)` vs `->source(null)`? I guess this is not the concern of the `source()` function.

**Comment by rhertogh** [comment]
@beowulfenator (and for future readers who might have the same question)
> No, i mean why would somebody who's using the library write `->source(false)` vs `->source(null)`? I guess this is not the concern of the `source()` function.

The `source()` function is used for "source filtering" and determines the content of `_source` field in the response body (https://www.elastic.co/guide/en/elasticsearch/reference/master/search-fields.html#source-filtering).
This way ElasticSearch document properties can be included or excluded in the response.
E.g. With `->source('is*')` the `_source` field would contain all properties starting with "is":
```
  "hits" : [
      {
        "_index" : "myIndex",
        "_type" : "_doc",
        "_id" : "123",
        "_source" : {
          "isPublished" : true,
          "isAvailable" : false
        }
      },
      ...
```

Setting `->source(null)` would disable the filtering for the `_source` field, in other word it would return all the document properties:

```
  "hits" : [
      {
        "_index" : "myIndex",
        "_type" : "_doc",
        "_id" : "123",
        "_source" : {
          ...
          "slug": "my-slug",
          "isPublished" : true,
          "isAvailable" : false,
          "created_at" : 1524493148000,
          "updated_at" : 1547205892000,
          "first_published_on" : 1524493148000,
          ...
        }
      },
     ...
```

Sometimes no `_source` data is needed at all, for example when only the `_id` field is required.
In this case the `->source(false)` would be used. This tells ElasicSearch to completely omit it form the response:
```
  "hits" : [
      {
        "_index" : "myIndex",
        "_type" : "_doc",
        "_id" : "123"
      },
      ...
```
This greatly increases speed and reduces memory usage.

**Pull request merged**
