### PR TITLE
Handle 404 returned from GET index/_doc/1, avoid error

### PR DESCRIPTION
**Pull request by lubobill1990**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets #258 fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Shouldn't pull request be made against 2.1 branch?

**Comment by samdark** [comment]
The same change should be applied to 2.1.

**Comment by lubobill1990** [comment]
@samdark I have submitted the pull request as you mentioned. https://github.com/yiisoft/yii2-elasticsearch/pull/262

**Comment by beowulfenator** [comment]
Fixed elsewhere.

**Pull request closed without merging**
