### PR TITLE
fix infinite loop

### PR DESCRIPTION
**Pull request by GHopperMSK**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #201

### CODE REVIEW

**Comment by samdark** [comment]
Should be applied to 2.1 as well.

**Comment by samdark** [comment]
@AnticDroid would you please check if this fix helps?

**Comment by AnticDroid** [comment]
After applying changes for \yii\elasticsearch\ActiveDataProvider from 
https://github.com/yiisoft/yii2-elasticsearch/blob/edf5bbb58e38cfd4540b43b5f33a974fdc763134/ActiveDataProvider.php

 **problem disappear**

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
