### PR TITLE
Update Command.php

### PR DESCRIPTION
**Pull request by tibee**
Added Bulk feature

### CODE REVIEW

**Comment by dmitriybelyy** [comment]
When it will be approved? :-)

**Comment by cebe** [comment]
soon ;)

**Comment by beowulfenator** [comment]
@dmitriybelyy To quote the reference:
> The endpoints are /_bulk, /{index}/_bulk, and {index}/{type}/_bulk. When the index or the index/type are provided, they will be used by default on bulk items that don’t provide them explicitly.

It's important to implement these. Also, if you use the `{index}/{type}/_bulk`, there's no need to include index and type in every command in the batch (saves on traffic).

Also, possible actions are index, create, delete and update, and only index and delete are implemented.

Finally, you're using magic strings `"INDEX"` and `"DELETE"`, which would be better defined as class constants.

**Comment by beowulfenator** [comment]
Please consider my alternative implementation of bulk command: https://github.com/yiisoft/yii2-elasticsearch/pull/85.

**Comment by beowulfenator** [comment]
Superceded by https://github.com/yiisoft/yii2-elasticsearch/pull/85.

**Pull request closed without merging**
