### PR TITLE
Feature/command support aliases

### PR DESCRIPTION
**Pull request by Tezd**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | Deserialization of raw response when text/plain is supported, Added ability to work with aliases through Command class

### CODE REVIEW

**Comment by Tezd** [comment]
Good day. Can someone re-run build? Composer was timing out today.

**Comment by samdark** [comment]
Pushed the button. It said it was restarted but I'm not sure it is.

**Comment by Tezd** [comment]
@samdark it seems that hhvm build has some problems with environment variables. Not sure that i can fix them from my side.
```
 [UnexpectedValueException]                                              

  Your github oauth token for github.com contains invalid characters: ""
```

**Comment by samdark** [comment]
We'll need unit tests for the methods added and phpdoc for each one.

**Comment by beowulfenator** [comment]
@Tezd 
The token will work once the request is merged. This is a limitation of github and travis-ci integration. If you can come up with a better solution, i'm open to suggestions.

**Pull request merged**
