### PR TITLE
Fix TODO indices-update-settings

### PR DESCRIPTION
**Pull request by githubjeka**
Add functions:
- `updateSettings()` for update settings of indices
- `updateAnalyzers` for update analysis of indices , as a special case.

### CODE REVIEW

**Comment by githubjeka** [comment]
Rel: https://github.com/yiisoft/yii2-elasticsearch/issues/27

**Comment by samdark** [comment]
Method descriptions needed.

**Comment by Alex-Bond** [comment]
+1

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
