### PR TITLE
Fix yiisoft/yii2#20202

### PR DESCRIPTION
**Pull request by lav45**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | yiisoft/yii2#20202

### CODE REVIEW

**Comment by samdark** [comment]
It will just install older version. It's better to fix the reason for such behavior.

**Comment by lav45** [comment]
@samdark I fixed the error, but the build still doesn't work. Also, we need to somehow reconcile the versions of yii2-elasticsearch and yii2, but I don't yet understand how. yii2:2.0.50 works with php>=7.4, while yii2-elasticsearch requires php>=5.6.

**Comment by terabytesoftw** [comment]
> @samdark I fixed the error, but the build still doesn't work. Also, we need to somehow reconcile the versions of yii2-elasticsearch and yii2, but I don't yet understand how. yii2:2.0.50 works with php>=7.4, while yii2-elasticsearch requires php>=5.6.

https://github.com/yiisoft/yii2-elasticsearch/pull/346 review this pr.

**Comment by samdark** [comment]
@terabytesoftw merged. @lav45 can you resolve conflicts please?

**Comment by terabytesoftw** [comment]
I can confirm that the latest ActiveDataProvider change resolves the segmentation issue in ElasticSearch.

https://github.com/terabytesoftw/yii2-elasticsearch/actions/runs/9546397753/job/26309179454

**Comment by samdark** [comment]
@terabytesoftw you mean this PR isn't needed?

**Comment by terabytesoftw** [comment]
> @terabytesoftw you mean this PR isn't needed?

I'm saying that now the fix works with https://github.com/yiisoft/yii2/pull/20206

**Comment by samdark** [comment]
@terabytesoftw seems elastic search doesn't build anymore :(

**Comment by samdark** [comment]
@lav45 can you add a line for CHANGELOG? Thanks.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
