### PR TITLE
[dont merge] Fix travis build

### PR DESCRIPTION
**Pull request by machour**
Trying to understand why Travis builds have been failing for so long.

### CODE REVIEW

**Comment by beowulfenator** [comment]
I believe this has to do with building certain test servers from source. We are testing for a bunch of different platforms (like different versions of ES and PHP) and some of them are configured to be pulled in from github. (It could also be composer-related, I'm not sure). Anyway, after a certain number of installations github asks for a key. At some point I've tried hardcoding my own key in there, and it seemed to have solved the problem, at least temporarily.

**Comment by machour** [comment]
@samdark I see that builds on master have been failing for a long time, and there's a 2.1 branch in this repo with another failure.

Could you bring me up to date with the situation of this repo? We need running tests before attempting to fix  #201

**Comment by machour** [comment]
@beowulfenator with the composer.json change I just made, the problem now seems to be an incompatibility between ES & Yii on dev-master: https://travis-ci.org/yiisoft/yii2-elasticsearch/jobs/480761513

**Comment by beowulfenator** [comment]
There are multiple versions of PHP, multiple versions of ES and multiple versions of Yii we should test against. Is it really worth testing all of those combinations?

**Comment by machour** [comment]
If Yii is supposed to provide support for them, then the answer should be "Yes it is" I guess :)

**Comment by machour** [comment]
If it helps pin-pointing the problem, I guess we should try to fix tests for one version of PHP & one version of ES first, and then gradually introduce other combinations. 

I'm first trying to understand whether efforts should be put it `master` or `2.1` before digging any further. If you have some experience with ES (I don't) your help would be greatly appreciated!

**Comment by samdark** [comment]
> Cluster autodetection did not find any active node. Make sure a GET /_nodes reguest on the hosts defined in the config returns the "http_address" field for each node.

Looks like the instance wasn't started or was started with non-default address.

**Comment by machour** [comment]
Also seems to be related to the ES version, check https://github.com/yiisoft/yii2-elasticsearch/issues/177#issuecomment-377337412

Is branch 2.1  meant for what we now call Yii 3, or is it a branch aiming at targeting more recent ES versions?

If it's the later, are we going to accept PRs for both `master` and `2.1` on this repo?

**Comment by samdark** [comment]
No. 2.1 is for ES versions. See readme.

**Comment by samdark** [comment]
I think it worth releasing 2.0.6 and then moving on to 2.1.0 releases. If there will be need to do 2.0.7 we can create 2.0 branch and do releases from there.

**Comment by samdark** [comment]
#208

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-elasticsearch/pull/210

**Comment by machour** [comment]
What about #206? Is it fixed by #201 or is another regression?

**Comment by samdark** [comment]
Fix was applied to https://github.com/yiisoft/yii2-elasticsearch/pull/210

**Pull request closed without merging**
