### PR TITLE
Few updates to phpdoc, and add missing requirements to composer.json

### PR DESCRIPTION
**Pull request by My6UoT9**
- adds `ext-mbstring` and `ext-json` to composer.json as  requirements.
- fixes missing phpdocs and a small typo.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by beowulfenator** [comment]
Looks good, but why do tests fail?

**Comment by samdark** [comment]
@beowulfenator that's workflow cache issues, not ES failure.

**Comment by samdark** [comment]
Thanks.

**Review by beowulfenator — APPROVED** [review]
I just hope that failing tests are an intermittent issue, and not related to adding those lines to `composer.json`.

**Comment by samdark** [comment]
They're fine. See build in master. It failed as well but differently. That's bad but not related to the pull request.

**Pull request merged**
