### PR TITLE
2.1

### PR DESCRIPTION
**Pull request by i-lie**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | 
| Tests pass?   | 
| Fixed issues  |

In Elasticsearch 5.x, the "Contect-Type" header is kinda required. If it isn't provided, it will display a warning in the deprecation.log file. This fix assumes that the request is always in JSON format. Not quite sure if there is another format besides JSON when sending a request to Elasticsearch.

### CODE REVIEW

**Comment by cebe** [comment]
Thank you!

**Comment by samdark** [comment]
Changelog?

**Comment by cebe** [comment]
working on it, there is none in the 2.1 branch right now.

**Comment by miroslav-chandler** [comment]
Guys, please make the release with fixed content type detection bug. The current release not working with elastic 6.0

**Comment by cebe** [comment]
2.1 is not ready for release yet.

**Pull request merged**
